// Mocks generated by Mockito 5.4.4 from annotations
// in elevate_online_exam/test/domain/usecases/authentication/register_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_online_exam/common/api_result.dart' as _i4;
import 'package:elevate_online_exam/data/api/models/request/auth_body.dart'
    as _i7;
import 'package:elevate_online_exam/domain/models/user.dart' as _i5;
import 'package:elevate_online_exam/domain/repos/authentication_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthenticationRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepo extends _i1.Mock
    implements _i2.AuthenticationRepo {
  MockAuthenticationRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User?>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> register(
    String? username,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            firstName,
            lastName,
            email,
            password,
            rePassword,
            phone,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #register,
            [
              username,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<String>> forgotPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i3.Future<_i4.Result<String>>.value(
            _i6.dummyValue<_i4.Result<String>>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<bool>> verifyResetPassword(String? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetPassword,
          [resetCode],
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #verifyResetPassword,
            [resetCode],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> resetPassword(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            newPassword,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #resetPassword,
            [
              email,
              newPassword,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> editProfile(_i7.AuthBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [body],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #editProfile,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);
}
