// Mocks generated by Mockito 5.4.4 from annotations
// in elevate_online_exam/test/presentaion/views/register/register_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:elevate_online_exam/common/api_result.dart' as _i6;
import 'package:elevate_online_exam/domain/models/user.dart' as _i7;
import 'package:elevate_online_exam/domain/repos/authentication_repo.dart'
    as _i2;
import 'package:elevate_online_exam/domain/usecases/authentication/register_usecase.dart'
    as _i4;
import 'package:elevate_online_exam/presentaion/views/register/register_validator/register_field_type_enum.dart'
    as _i10;
import 'package:elevate_online_exam/presentaion/views/register/register_validator/register_validator.dart'
    as _i9;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationRepo_0 extends _i1.SmartFake
    implements _i2.AuthenticationRepo {
  _FakeAuthenticationRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_2<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RegisterUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUsecase extends _i1.Mock implements _i4.RegisterUsecase {
  MockRegisterUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepo get authenticationRepo => (super.noSuchMethod(
        Invocation.getter(#authenticationRepo),
        returnValue: _FakeAuthenticationRepo_0(
          this,
          Invocation.getter(#authenticationRepo),
        ),
      ) as _i2.AuthenticationRepo);

  @override
  set authenticationRepo(_i2.AuthenticationRepo? _authenticationRepo) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticationRepo,
          _authenticationRepo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.Result<_i7.User?>> invoke(
    String? username,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [
            username,
            firstName,
            lastName,
            email,
            password,
            rePassword,
            phone,
          ],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.User?>>.value(
            _i8.dummyValue<_i6.Result<_i7.User?>>(
          this,
          Invocation.method(
            #invoke,
            [
              username,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.User?>>);
}

/// A class which mocks [RegisterValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterValidator extends _i1.Mock implements _i9.RegisterValidator {
  MockRegisterValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TextEditingController get usernameController => (super.noSuchMethod(
        Invocation.getter(#usernameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#usernameController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get firstnameController => (super.noSuchMethod(
        Invocation.getter(#firstnameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#firstnameController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get lastnameController => (super.noSuchMethod(
        Invocation.getter(#lastnameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#lastnameController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get emailController => (super.noSuchMethod(
        Invocation.getter(#emailController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#emailController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get passwordController => (super.noSuchMethod(
        Invocation.getter(#passwordController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#passwordController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get confirmPasswordController =>
      (super.noSuchMethod(
        Invocation.getter(#confirmPasswordController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#confirmPasswordController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get phoneNumberController => (super.noSuchMethod(
        Invocation.getter(#phoneNumberController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#phoneNumberController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.GlobalKey<_i3.FormState> get formKey => (super.noSuchMethod(
        Invocation.getter(#formKey),
        returnValue: _FakeGlobalKey_2<_i3.FormState>(
          this,
          Invocation.getter(#formKey),
        ),
      ) as _i3.GlobalKey<_i3.FormState>);

  @override
  String? Function(String?) validate(_i10.RegisterFormFieldType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #validate,
          [type],
        ),
        returnValue: (String? __p0) => null,
      ) as String? Function(String?));
}
